import { McpAgent } from "agents/mcp";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { addNoteToLead, getLead, moveLead, pauseLeadAgent } from "./tools/leads";
import { canUseTool } from "./utils/canUseTools";

export class MyMCP extends McpAgent {
	server = new McpServer({
		name: "Kommo MCP",
		version: "1.0.0",
	});

	private getConfig() {
		return (this as any).props;
	}

	async init() {

		const kommoCLient = this.getConfig();

		/*──────────────── move_lead ────────────────*/
		if (canUseTool(kommoCLient, "move_lead")) {
			this.server.tool(
				"move_lead",
				"This tool is useful when you need to move a lead to a different pipeline.",
				{
					lead_id: z
						.number()
						.describe("Unique ID assigned by Kommo CRM to the lead. This identifier is used to fetch all related information for a specific lead within the system."),
					pipeline_id: z
						.number()
						.describe("ID of the pipeline where the lead should be moved."),
					status_id: z
						.number()
						.describe("ID of the stage within the target pipeline where the lead should be placed.")
				},
				async ({ lead_id, pipeline_id, status_id }) => {
					try {

						const lead = await getLead(lead_id, kommoCLient);

						if (lead === null) {
							return {
								content: [
									{
										type: "text",
										text: "Failed to move lead: the specified lead does not exist in Kommo."
									}
								]
							}
						}

						const res = await moveLead(lead_id, pipeline_id, status_id, kommoCLient);

						if (res === null) {
							return {
								content: [
									{
										type: "text",
										text: "Failed to move lead: Kommo did not accept the update request."
									}
								]
							}
						}

						return {
							content: [
								{
									type: "text",
									text: "Lead successfully moved to the specified pipeline and status."
								}
							]
						}

					} catch (error) {
						console.error("💥 [move_lead] Error:", error);
						return {
							content: [
								{
									type: "text",
									text: `Error al mover el lead: ${(error as Error).message || error}`
								}
							]
						}
					}
				}
			);
		}

		/*──────────────── pause_agent ──────────────*/
		if (canUseTool(kommoCLient, "pause_agent")) {
			this.server.tool(
				"pause_agent",
				"This tool pauses the assigned agent for a specific lead.",
				{
					lead_id: z
						.number()
						.describe("Unique ID assigned by Kommo CRM to the lead. This identifier is used to fetch all related information for a specific lead within the system."),
						switch_field_id: z
						.number()
						.describe("ID of the switch field to pause for this lead."),
						switch_field_value: z
						.boolean()
						.describe("Status of the switch field to pause for this lead.")
				},
				async ({ lead_id, switch_field_id, switch_field_value = false }) => {
					try {

						const lead = await getLead(lead_id, kommoCLient);

						if (lead === null) {
							return {
								content: [
									{
										type: "text",
										text: "Failed to pause agent: the specified lead does not exist in Kommo."
									}
								]
							}
						}

						const res = await pauseLeadAgent(lead_id, switch_field_id, switch_field_value, kommoCLient);

						return {
							content: [
								{
									type: "text",
									text: "Agent successfully paused for the specified lead."
								}
							]
						}

					} catch (error) {
						console.error("💥 [pause_agent] Error:", error);
						return {
							content: [
								{
									type: "text",
									text: `Error al pausar el agente: ${(error as Error).message || error}`
								}
							]
						}
					}
				}
			);
		}

		/*──────────────── add_note ──────────────*/
		if (canUseTool(kommoCLient, "add_note")) {
			this.server.tool(
				"add_note",
				"This tool adds a note to a specific lead in Kommo, storing contextual or summarized information directly in the lead’s activity history.",
				{
					lead_id: z
						.number()
						.describe("Unique ID assigned by Kommo CRM to the lead. This identifier is used to fetch all related information for a specific lead within the system."),
					note: z
						.string()
						.describe("A concise note generated by the agent based on the full conversation, summarizing the key points, user intent, and any relevant context to be stored in the lead’s history.")
				},
				async ({ lead_id, note }) => {
					try {

						const res = await addNoteToLead(lead_id, kommoCLient, note);

						if (res === null) {
							return {
								content: [

									{
										type: "text",
										text: "Error adding the note."
									}
								]
							}
						}

						return {
							content: [
								{
									type: "text",
									text: "Note added succesfully."
								}
							]
						}

					} catch (error) {
						console.error("💥 [add_note] Error:", error);
						return {
							content: [
								{
									type: "text",
									text: `Error al añadir nota al lead: ${(error as Error).message || error}`
								}
							]
						}
					}
				}
			)
		}

	}
}